### ISSUE TITLE
Remove Internal/External error wrappers used in `AppErrorType`

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#110]
I think we will need a new constructor for `AppErrorType` for errors that might be thrown by the `MonadDownload` effect.
```
newtype AppErrorType = DownloadError DError
    deriving (Show, Eq)
```
And also helper function for converting the `Status` type in https://hackage.haskell.org/package/http-types-0.12.3/docs/Network-HTTP-Types-Status.html#t:Status to `AppErrorType`. I think we will need this, but `200` status is not an error so...We also need logging but this is a separate issue.

**Comment by chshersh** [comment]
@rashadg1030 I'm starting to worry about inconsistency of our error data types. I would like to have some rules whether we should add constructors to top-level `AppErrorType` or to one of the constructors of this data type. For example, documentation to `InternalError` says the following:

https://github.com/kowainik/issue-wanted/blob/d614fdfeb11c99f33a054c6854c4886ca4180d43/src/IW/App/Error.hs#L89-L92

I think it makes sense instead of:

```haskell
data AppErrorType 
    = InternalError IError
    | GitHubError GError
```

Have something like that:

```haskell
data AppErrorType 
    = InternalError IError
    | ExternalError EError
```

But now, what is the distinction between `InternalError` and `ExternalError`? And if the distinction is subtle, do we really need it to overheat our brains each time when deciding to which data type we need to add constructors?

In `three-layer` this was done this way because there is a mobile application and we need to tell different errors to the mobile application, it handles it independently. But here it looks like all errors will be handled by us, frontend will just display errors. So why not remove `InternalError` and leave only `AppErrorType` with many constructors?

Any thoughts? @vrom911 @rashadg1030

**Comment by rashadg1030** [comment]
@chshersh I think this is a good idea 💡 It is annoying to have that extra wrapper and I don’t think it’s necessary. In my opinion it’s not really helpful to distinguish between Internal and External errors. All the constructors should probably fall under just AppErrorType.

**Comment by chshersh** [comment]
I think we reached consensus over this issue and this refactoring can be performed 🙂
