### ISSUE TITLE
Scaffold initial frontend

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#111]
Decide on frontend and scaffold initial structure.

**Comment by vrom911** [comment]
Some updates on this. In order to build `issue-wanted` with `ghcjs` we would need to move back to `8.4` compiler version. It means no `DerivingVia` or any other newer extensions or features. But this is not that critical at the moment in the project.

Another problem is that `base-noprelude` is not compatible with `ghcjs`. See [this issue](https://github.com/haskell-hvr/base-noprelude/issues/4). So most likely we would use our fork of `base-noprelude` library. Let me know if you have any better ideas. For now, I would continue with the fork.
