### ISSUE TITLE
Consider using named parameters in queries

### ISSUE THREAD

**Issue by vrom911** [kowainik/issue-wanted#118]
We can use [postgresql-simple-named](https://hackage.haskell.org/package/postgresql-simple-named) library for this.

**Comment by rashadg1030** [comment]
@vrom911 This is really cool. I agree we should introduce this.

**Comment by rashadg1030** [comment]
I was trying to look for an example, but can this be used with `executeMany`?

**Comment by chshersh** [comment]
@rashadg1030 We don't have `executeMany` implemented in `postgresql-simple-named` library... I've created an issue about that:

* https://github.com/Holmusk/postgresql-simple-named/issues/15

**Comment by chshersh** [comment]
I think that this issue is also unblocked. We can start using named parameters right now to avoid migration to this way later when there are more functions to refactor. So every SQL query that is not used under `executeMany` can be moved to use `queryNamed` or `executeNamed`. You can check `three-layer` to see how to perform this migration (it's not straightforward because you need to deal with `MonadError` parametrised by different types but possible).

* https://github.com/Holmusk/three-layer/blob/1b58ec102f206681b66a584ca4a7d18f2eb4ef81/src/Lib/Db/Functions.hs#L59-L67
