### ISSUE TITLE
Add `repoDefaultBranch` field to `Repo` type 

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#120]
We are downloading `cabal` files for repos. In order to get the correct `cabal` file, we need to know the default branch of the repo. We can get the default branch of the repo via the `github` library. We could call the `github` library each time we need the default branch (each time we download a `cabal` file), but we would go over the rate limit of the API. Instead, we could add a `repoDefaultBranch` to the `Repo` type and use it when needed. We would construct the repos the way we do now, but we just add `repoDefaultBranch`. If we are going to store the default branch we might as well store the URL for the `cabal` file for each repo. This is my logic for adding `repoCabalUrl` to the `Repo` type. Our function `fromGitHubRepo :: GitHub.Repo -> Repo` would get the `defaultBranch` and we would construct the `Repo` with this field. The thing is `defaultBranch` on `GitHub.Repo` returns a `Maybe Text`:
https://hackage.haskell.org/package/github-0.22/docs/GitHub-Data-Repos.html
If it returns nothing, the default branch should be `master`. We would have to modify a few functions, but not much.

Refer to this comment for more about the reason for this issue:
https://github.com/kowainik/issue-wanted/pull/119#discussion_r302806720

**Comment by chshersh** [comment]
@rashadg1030 It's nice that `Repo` data type has a default branch! But, as I said, this is not a priority. I don't expect there to be many repositories which have non-standard branches. So let's not spend time on this. In a perfect world, it would be nice to have some statistics about repos we can't fetch info about and the reasons why we can't do that so we can prioritise problems better. My initial guess would be that the majority of problems with updating repos will be because of `package.yaml` instead of `.cabal` file.

**Comment by rashadg1030** [comment]
Now that I added the new field to the `Repo` type, I must update the SQL schema. Will do this tomorrow.
