### ISSUE TITLE
GitHub API Query Functions

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#20]
I've made a fork of the project and have been testing the GitHub API query functions located in issue-wanted/src/IssueWanted/Search.hs. None of the functions return errors which is great, but I'm not sure if they are returning the right results. For example, the function `fetchHaskellReposGFI`, which returns all Haskell repositories with "good-first-issue" labels, gives a result count of 124. The function `fetchGoodFirstIssue`, which is supposed to return all issues with Haskell language and label "good-first-issue", only gives a result count of 8. This seems odd to me, but I'm not sure. There may be a problem with the query strings passed into `searchRepos` or `searchIssues`, but I can't be sure until I look more into the GitHub API documentation. I just wanted to get someone else's opinion on this issue.

**Comment by ChShersh** [comment]
@rashadg1030 I think it's better to create minimal example and open issue for GitHub repo. But the chances is that you see lower number of results due to pagination. Though, number 8 looks too small for that. So it is still a good idea to ask about the behavior under `github` package:

* https://github.com/phadej/github/issues

**Comment by rashadg1030** [comment]
@ChShersh Okay that makes sense. I'll do some more research. Thank you.
