### ISSUE TITLE
Setup testing suite

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#33]
I would like to work on setting up the testing suite before I start making any serious changes to the code. Should I refer to the `three-layer` example tests? If so, will we need `hedgehog` for testing or is `hspec` enough?

**Comment by chshersh** [comment]
@rashadg1030 Yes, `hspec` and `hedgehog` will be enough. We don't have any functionality to test now. But after we implement some functions,we need to setup the testing as well.

**Comment by chshersh** [comment]
@rashadg1030 I propose to prioritize this issue. Since we now have testing configured both locally and on CI via Docker contains, we actually can start writing tests. You can see how it's done in `three-layer`. You need to copy-paste some util modules from the `test/` directory but after that, you can start writing unit tests for functions you implement.

The only problem I see now is that you will probably write more tests that we actually need. For example, I don't think we need a function `getIssueById` because in the `issue-wanted` we never work with individual issues. I think there won't be any page that allows you to see the details of a single issue. If you want the details -- you just click on the link that redirects you to GitHub. We will work only with lists of issues.

But other than that, you can start writing tests at least for all SQL-related functions.
