### ISSUE TITLE
Implement SQL join statements

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#42]
I was thinking because we have join tables we should implement some join statements in the `sql/join.sql` file. Is this a good idea? I'm currently doing some research on SQL joins.

**Comment by chshersh** [comment]
@rashadg1030 I think we don't need to implement join statements in the separate SQL file. This is just an SQL query and we are going to use `postresql-simple` to write such queries. In simple words, instead of querying from a single table like this:

```haskell
SELECT * FROM issues
```

We will just join `issues` table with `labels` table like this:

```haskell
SELECT *
FROM issues
LEFT JOIN labels ON issues.id = labels.issue_id
```

**Comment by rashadg1030** [comment]
@chshersh Got it!

**Comment by chshersh** [comment]
@rashadg1030 I think in that case this is not really an issue.
