### ISSUE TITLE
Retrieve category from repository Cabal file

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#43]
We can use the GitHub API to retrieve the contents of a repo's Cabal file. For example pandoc: https://api.github.com/repos/jgm/pandoc/contents/pandoc.cabal

We can then use 
https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/Distribution-PackageDescription-Parsec.html
to parse the file once we retrieve it.

Anything I'm missing anything or suggestions??

**Comment by chshersh** [comment]
Instead of using GitHub API we can use `curl` to download raw content of the file. If we use GItHub API too often, we can hit the request limit.

Regarding parsing: yep, we will use `Cabal` library to parse `.cabal` files. For now we will fetch only categories, but later we can extract more metadata from the file.

There are two potential problems for this approach:
1. Some Haskell packages use `hpack` and `package.yaml` and don't store `.cabal` files on GitHub. For now we are not going to support such packages, just ignore fetching categories for them.
2. Some repositories are multipackage Haskell packages. We are going to ignore them for now as well.

**Comment by rashadg1030** [comment]
https://hackage.haskell.org/package/download 
The above looks like a nice library for downloading a .cabal file. Not sure how it compares with `curl` though. The build isn't passing so maybe not so good. 

https://api.github.com/repos/jgm/pandoc/contents/pandoc.cabal
And I had a question about constructing queries:
We need the repo owner name in the query url, so should we store repo owner in our DB as well? So when we need to get the `.cabal` we have the name. And is the convention for `.cabal` files always 
`<package_name>.cabal`. If so, I guess it is fine to just append `repo_name` (we have in our DB) to `.cabal` and attach it to the end of the query string.

**Comment by chshersh** [comment]
> We need the repo owner name in the query url, so should we store repo owner in our DB as well?

Yes, we can do that, shouldn't be any problems. If the search query returns us the owner as well.

Regarding the `download` library: I never heard about it. Reverse dependencies show that this library is not used much, so probably not so popular and maybe not a good idea to use it:

* https://packdeps.haskellers.com/reverse/download

**Comment by rashadg1030** [comment]
[This](http://hackage.haskell.org/package/curl-1.3.2) is the library we can use to download `cabal` files.

**Comment by rashadg1030** [comment]
Does the name of the `cabal` file always match the name of the project? I guess we can start with this assumption.

**Comment by chshersh** [comment]
@rashadg1030 `curl` library doesn't look good as well. It returns `String` as a result is built around `String` type in general. Doesn't look efficient.

> Does the name of the cabal file always match the name of the project?

I think this is a false assumption. Consider the following repository:
* https://github.com/hedgehogqa/haskell-hedgehog

No to mention that not every Haskell repo can contain `.cabal` file...

**Comment by rashadg1030** [comment]
@chshersh oof. I saw Galois people were the maintainers, so I just assumed it was good. My mistake

**Comment by rashadg1030** [comment]
So the idea is to use the raw URL like so:
`https://raw.githubusercontent.com/kowainik/hit-on/master/hit-on.cabal`
Correct?
I'd like to tackle this issue, but can't find a `curl` library that uses `Text`. Are there alternatives to `curl`?

**Comment by rashadg1030** [comment]
Maybe there's a way to run a script. So use `curl` through `shellmet` perhaps? I don't know if this would work.

**Comment by rashadg1030** [comment]
http://hackage.haskell.org/package/download-curl
This library has `ByteString`.

**Comment by rashadg1030** [comment]
http://hackage.haskell.org/package/http-conduit-2.1.2.3/docs/Network-HTTP-Conduit.html
What about this? I would like some experience with `conduit` :slightly_smiling_face: .

**Comment by chshersh** [comment]
@rashadg1030 You can always ask on Reddit about the best library for downloading the file by `https` URL 🙂 Unfortunately, I'm not aware of the best library for our needs... So let's hear what the community thinks.

Regarding `download-curl`: the library was last updated in 2012, so it's probably not maintained, I wouldn't recommend to use it.

I looked again at the `download` library you suggested first: it uses `ByteString`, which is good, but it doesn't support HTTPS... 😞 

Regarding `shellmet`: yes, you actually can use this library and call shell commands. However, if you want to read a file in memory with `shellmet`, it won't be efficient because `shellmet` uses `readProcess` and this function works with `String`... Or you can call raw shell command to output the result to file, like:

```shell
curl <URL> > file.name
```

But this will result in having downloaded files locally, and proper resource-management code needs to be introduced not to leave garbage on disk.

Regarding `conduit`: well, this is a full power streaming library, it seems like an overkill to add it to our code just to download 100KB files 😄

Also, keep in mind the following things:

1. There might not be a file with the `.cabal` extension in the repo (`package.yaml` is used, multipackage project, other reasons), so the solution shouldn't fail sync worker if there is no such file. We just will log that this repository doesn't contain a file.
2. There might be a file with the `.cabal` extension, but the repo and Haskell package have different names. So to get this file, you need to scan directory...

Regarding 1: we need to solve it now. Regarding 2: I propose to create a separate issue and fix it only if we have time. I assume that in 80% of cases GitHub repo will have the same name as Haskell package, so this is good as a first approximation.

**Comment by chshersh** [comment]
@rashadg1030 Thanks for creating [a discussion on reddit](https://www.reddit.com/r/haskell/comments/cavfnh/recommended_library_for_downloading_files_via/) (though, there wasn't a lot of comments). I looked at all options and here is what I'm proposing to use to download `.cabal` file contents.

1. [`httpLbs`](https://hackage.haskell.org/package/http-client-0.6.4/docs/Network-HTTP-Client.html#v:httpLbs) function from `http-client`.
2. This function should take the result of the [`newTlsManager`](https://hackage.haskell.org/package/http-client-tls-0.3.5.3/docs/Network-HTTP-Client-TLS.html#v:newTlsManager) (from `http-client-tls` library) as an argument of the `Manager` type.

I looked at the code for `httpBS` and it doesn't use any `conduit` capabilities:

```haskell
httpBS :: MonadIO m => H.Request -> m (H.Response S.ByteString)
httpBS req = liftIO $ do
    man <- H.getGlobalManager
    fmap L.toStrict `fmap` H.httpLbs req man
```

So no need to add heavy extra dependencies to our project, we can write the same two lines of code and even better 🙂 

`getGlobalManager` is a dark Haskell magic to introduce global mutable variables:

```haskell
-- | Evil global manager, to make life easier for the common use case
globalManager :: IORef Manager
globalManager = unsafePerformIO $ newTlsManager >>= newIORef
{-# NOINLINE globalManager #-}

-- | Get the current global 'Manager'
--
-- @since 0.2.4
getGlobalManager :: IO Manager
getGlobalManager = readIORef globalManager
{-# INLINE getGlobalManager #-}
```

But since we are using `ReaderT` as our application monad, we can create `Manager` and put it inside our environment and get it from the environment instead of getting from a global mutable variable. I think it's time for you to practice in creating custom effects 😏 I will create a separate issue for that.
