### ISSUE TITLE
Describe all API endpoints we need from GitHub

### ISSUE THREAD

**Issue by chshersh** [kowainik/issue-wanted#5]
Basically we need:

- [x] List of all Haskell repositories
```
curl -H 'Accept: application/vnd.github.preview.text-match+json' https://api.github.com/search/repositories?q=language:haskell&order=desc
```

- [ ] For each repository: list of issues by given label (`help wanted`, `good first issue`)
    + **TODO**: insert Rest API method here
- [ ] For each user: each PR for this user
    + **TODO**: insert Rest API method here
- [ ] For each PR: which issue it closes
    + **TODO**: insert Rest API method here

**Comment by willbasky** [comment]
> For each user: each PR for this user

`For each user` on our site or at GitHub? Could it described more?

**Comment by ChShersh** [comment]
@willbasky In this context `For each X` means _provide function `X -> Smth`_. We need to know how to fetch information about user. And then we can easily fetch this information for multiple users. But what is the set of users we're interested in – is another task.

**Comment by rashadg1030** [comment]
@ChShersh We have a working GitHub query function `fetchAllHaskellRepos` that returns a vector of repos. Would it be fine to write a function that takes a repo and returns a list/vector of issues with the `help wanted`/`good first issue` labels? `Repo -> [Issues]` for example.

**Comment by ChShersh** [comment]
@rashadg1030 I think it's too early to think about this. Also see issue #21, some parts of the architecture might change before project starts.

**Comment by rashadg1030** [comment]
@ChShersh Alright, thank you. I will look more into issue #21. I think it is a good idea.

**Comment by rashadg1030** [comment]
@chshersh I would like to discuss more the type of endpoints we will be exposing and the data that they represent. Maybe we could start listing endpoints that we think issue-wanted should have?

**Comment by rashadg1030** [comment]
##For each repository: list of issues by given label (help wanted, good first issue):

1. https://api.github.com/repos/:repo_owner/:repo_name/issues?labels=help-wanted
2. https://api.github.com/repos/:repo_owner/:repo_name/issues?labels=good-first-issue

##For each user: each PR for this user:

Interesting Stack Overflow comment I found regarding this issue

`First you have to realize that you must authenticate using either Basic Authentication or a token. Next you have to realize that there is no simple way to do this so you will have to be clever.
To be specific, if you probe https://api.github.com/issues, you'll notice that the issues there have a hash called pull_request which should have 3 URLs: html, diff, and patch. All three will be non-null if the issue is also a Pull Request. (Pro-tip: They're the same thing as far as GitHub is concerned…sort of.)`

I'm not sure if it is possible to access other users issues without authentication which is kind of odd. Maybe I'm doing something wrong?

##For each PR: which issue it closes

1. https://api.github.com/repos/:repo_owner/:repo_name/pulls/:pull_number
Get the PR
2. Then get the `issue-url` from the response to get the issue the PR closes.
They're maybe a better endpoint for this so we can skip the second step, but this is what I found so far.

**Comment by chshersh** [comment]
@rashadg1030 Great job! Let's not focus on the user-part and PR-related part yet, since we are not going to implement user authentication now. But your work is useful and the comment can be used later as a reference once we get to it. What we want right now:

1. A search query that returns all Haskell repositories.
2. A search query that returns all Haskell open issues.
3. The same as 2 but takes a list of labels and returns all Haskell issues with the specified labels

**Comment by rashadg1030** [comment]
1. A search query that returns all Haskell repositories.
https://api.github.com/search/repositories?q=language:haskell

2. A search query that returns all Haskell open issues.
https://api.github.com/search/issues?q=language:haskell+is:open

3.  The same as 2 but takes a list of labels and returns all Haskell issues with the specified labels
https://api.github.com/search/issues?q=language:haskell+is:open+label:enhancement+label:refactoring
