### ISSUE TITLE
Implement WithId type

### ISSUE THREAD

**Issue by rashadg1030** [kowainik/issue-wanted#89]
How will this work?

**Comment by chshersh** [comment]
The data type looks like this:

```haskell
data WithId a = WithId
    { withIdId  :: !(Id a)
    , withIdVal :: !a
    }
```

It will have `FromRow/ToRow` instances using [`:.`](http://hackage.haskell.org/package/postgresql-simple-0.6.2/docs/Database-PostgreSQL-Simple.html#t::.) data type.

After that, you can derive `ToRow` and `FromRow` for both `Repo` and `Issue` automatically. But lets keep our property-tests using `WithId` instead of raw `:.`. So we will be sure that everything works.
